application:
  version: 0.1.0
server:
  port: 1018
  servlet:
    context-path: /commons
  tomcat:
    uri-encoding: utf-8
spring:
  redis:
    database: 2
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-idle: 6
        max-active: 32
        max-wait: 100ms
        min-idle: 4
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: test
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    druid:
      # 数据库访问配置, 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
#      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      url: jdbc:mysql://**.**.**.**:***/lechi?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
#      url: jdbc:p6spy:mysql://49.234.11.97:33306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
      username: abc
      password: abc
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 连接等待超时时间
      max-wait: 30000
      # 配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙
      filters: stat,slf4j,wall
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
#      aop-patterns: com.ethanzyc.commons.business.mapper.*

      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      # StatViewServlet配置
      stat-view-servlet:
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 需要账号密码才能访问控制台
        login-username: druid
        login-password: druid123
        # IP白名单
        # allow: 127.0.0.1
        #　IP黑名单（共同存在时，deny优先于allow）
        # deny: 192.168.1.218

      # 配置StatFilter
      filter:
        stat:
          enabled: true
          log-slow-sql: true
#          PrintSqlFilter 中的 maxTime 也需要修改
          slow-sql-millis: 1000
          db-type: mysql
          merge-sql: true
#        commons-log:
#          statement-log-enabled: true
#          statement-executable-sql-log-enable: true
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-log-enabled: false
          statement-executable-sql-log-enable: true
          statement-log-error-enabled: true
          result-set-log-enabled: true
  profiles:
    active: dev

  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
# https://blog.csdn.net/hry2015/article/details/75451705
# https://juejin.im/post/5cf726abf265da1b70049688
  cache:
    type: redis

# slf4j日志配置
logging:
  level:
    web: debug
    #分包配置级别，即不同的目录下可以使用不同的级别
    com.ethanzyc.commons: debug
# 指定输出日志的文件名，默认输出至当前项目目录下
#  path: logs
#  file: mylog.log
#  pattern:
#    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
#    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'

mybatis-plus:
  mapper-locations: classpath*:com/ethanzyc/commons/business/mapper/xml/*.xml
  global-config:
    db-config:
      field-strategy: not_empty
      id-type: auto
      db-type: mysql
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "




